import {privacyNotice,consentRecord} from './privacy.mjs';
import {choiceHistory,appFeedbackFields} from './reflection.mjs';
import {purchasePlan2,START,SCENES2,fresh2,value2,actions2,step2,support2,restore2,continueFrom1,price2,leveragePrice2,changes2,bill2,health2,cashShort2} from './stage2-engine.mjs?v=start-250-1';
const app=document.querySelector('#app'),KEY=location.pathname.endsWith('/preview-stage2.html')?'prototype-stage2-preview':'prototype-campaign-stage2-v2',money=n=>Math.round(n).toLocaleString('ko-KR')+'원';
let s,onRestart;let forwardStates=[];
const short=n=>`${Number((n/10000).toFixed(1)).toLocaleString('ko-KR')}만 원`;
let openResource=null;
function appFeedbackUsed(){try{return localStorage.getItem('prototype-app-feedback-stage2')==='yes';}catch{return false;}}
export function resumeStage2(previous,price,restart,force=false){
 let saved;try{saved=JSON.parse(localStorage.getItem(KEY));}catch{}
 if(!force&&(!saved||saved.sourceSignature!==JSON.stringify(previous)))return false;
 if(saved&&saved.version!==2){try{localStorage.setItem(KEY+'-credit-backup',JSON.stringify(saved));}catch{}}
 const restored=saved?restore2(JSON.stringify(saved)):null;
 s=restored?.sourceSignature===JSON.stringify(previous)?restored:continueFrom1(previous,price);
 forwardStates=[];s=health2(s);s.needSurveyShown=(s.answers||[]).some(a=>a.kind==='reflection-need'||(!a.kind&&a.amount===5000000));try{if(localStorage.getItem('prototype-feedback-used-stage2')==='yes')s.needSurveyShown=true;}catch{}onRestart=restart;save();render();return true;
}
export function clearStage2(){try{localStorage.removeItem(KEY);}catch{}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(s));}catch{}}
function row(label,value){return `<div><span>${label}</span><strong>${value}</strong></div>`;}
function hud(){const v=value2(s),bill=SCENES2.slice(s.turn).find(x=>x.kind==='bill'),due=s.phase==='result'?0:(bill?.bill||0)+(s.medical?.bill>=s.turn&&SCENES2[s.medical.bill]===bill?500000:0);
const entries=[
 ['cash','남은 현금',short(s.cash),'<path d="M5 9h20v17H5zM8 9V5h14v4"/><path d="M19 15h8v6h-8z"/><circle cx="22" cy="18" r="1" fill="currentColor" stroke="none"/>','주식을 팔지 않고 바로 사용할 수 있는 돈입니다.'],
 ['expense',due?'예정 생활비':'결제 예정 없음',due?short(due):'없음','<path d="M8 4h16v24l-4-3-4 3-4-3-4 3zM12 10h8M12 15h8M12 20h4"/>',due?`다음 생활비는 ${money(due)}입니다. ${s.cash<due?`현금이 ${money(due-s.cash)} 부족합니다.`:'현재 현금으로 결제할 수 있습니다.'}`:'남은 예정 생활비가 없습니다.'],
 ['ratio','투자금',short(v.stock),'<path d="M17 4v12h12A12 12 0 0 0 17 4Z" fill="currentColor" stroke="none"/><path d="M12 8a11 11 0 1 0 12 12H12Z"/>',`삼성전자와 레버리지 상품의 현재 평가금액을 합한 금액입니다. 레버리지 상품은 매 턴 삼성전자 변동률의 2배로 움직이도록 만든 학습용 가상 상품입니다. 전체 기간의 수익률이 항상 2배인 것은 아닙니다.`],
 ['health','건강',`${s.health??80} / 100`,'<path d="M16 27 5 16C-2 7 10 0 16 9 22 0 34 7 27 16Z"/><path d="M8 16h5l2-5 3 10 2-5h4"/>','쉬면 건강이 15 회복됩니다. 건강이 40 이하가 되면 이 스테이지에서 한 번, 다음 생활비에 병원비 50만 원이 추가됩니다.']];
return `<div class="resource-wrap"><div class="hud icon-hud">${entries.map(([key,name,value,icon,description])=>`<button type="button" class="resource-button ${key==='expense'&&s.cash<due?'warning':''}" data-stage2-resource="${key}" aria-label="${name}: ${value}. 자세히 보기"><svg viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">${icon}</svg><span class="resource-name">${name}</span><strong class="investment-value">${value}</strong>${key==='expense'&&s.cash<due?`<small class="icon-warning">${short(due-s.cash)} 부족</small>`:''}</button>`).join('')}</div><dialog id="resource-detail"><div class="resource-detail-head"><strong>${entries.find(x=>x[0]===openResource)?.[1]||''}</strong><button type="button" data-stage2-close aria-label="설명 닫기">×</button></div><div class="resource-popup-value">${entries.find(x=>x[0]===openResource)?.[2]||''}</div><p>${entries.find(x=>x[0]===openResource)?.[4]||''}</p></dialog></div>`;
}
function holdingsIndicator(){
 const v=value2(s),change=changes2(s),pct=n=>`${n>0?'+':''}${n.toFixed(1)}%`;
 return `<div class="product-holdings">${[['삼성전자',s.units,price2(s),v.samsung,change.normal],['2배 레버리지',s.leverUnits,leveragePrice2(s),v.leverage,change.leverage]].map(([name,units,price,total,delta])=>`<div class="product-holding"><div><strong>${name} · ${Number(units.toFixed(2))}주</strong><span class="${delta>=0?'up':'down'}">${s.turn?'이번 턴 '+pct(delta):'시작 가격'}</span></div><p>1주 ${money(price)}<span>보유 금액 ${short(total)}</span></p></div>`).join('')}</div>`;
}
function tradeChoices(){
 const available=actions2(s);
 return `<div class="choices trade-choices"><button class="choice" data-stage2-trade="buy" ${available.some(a=>['buy','leverBuy'].includes(a))?'':'disabled'}>산다<small>상품당 최대 100만 원</small></button><button class="choice" data-stage2-trade="sell" ${s.units||s.leverUnits?'':'disabled'}>판다<small>${s.units||s.leverUnits?'선택한 상품 전량 매도':'보유 상품 없음'}</small></button><button class="choice" data-stage2-action="rest">쉬어 간다<small>보유 유지 · 건강 +15</small></button></div>`;
}
function openTrade(kind){
 const available=actions2(s),options=(kind==='buy'?['buy','leverBuy']:['sell','leverSell']).filter(a=>available.includes(a));
 if(!options.length)return;
 if(kind==='sell'&&options.length===1){app.dispatchEvent(new CustomEvent('stage2-trade-selected',{detail:options[0]}));return;}
 if(kind==='buy'){openBuyPicker(options);return;}
 const dialog=document.createElement('dialog');dialog.id='trade-picker';dialog.setAttribute('aria-labelledby','trade-picker-title');
 dialog.innerHTML=`<div class="resource-detail-head"><strong id="trade-picker-title">${kind==='buy'?'어떤 상품을 살까요?':'어떤 상품을 팔까요?'}</strong><button type="button" data-trade-close aria-label="상품 선택 닫기">×</button></div><p class="notice">${kind==='buy'?'상품을 선택하면 최대 100만 원을 매수합니다.':'상품을 선택하면 해당 상품을 전량 매도합니다.'}</p><div class="trade-products">${options.map(a=>`<button class="choice" data-stage2-action="${a}">${a.startsWith('lever')?'2배 레버리지':'삼성전자'}<small>${kind==='buy'?'최대 100만 원':money(a==='sell'?value2(s).samsung:value2(s).leverage)+' 전량 매도'}</small></button>`).join('')}</div><button type="button" class="text-button" data-trade-close>취소</button>`;
 app.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.querySelectorAll('[data-trade-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.showModal();
}
function openBuyPicker(options){
 const dialog=document.createElement('dialog');dialog.id='trade-picker';dialog.setAttribute('aria-labelledby','trade-picker-title');
 dialog.innerHTML=`<div class="resource-detail-head"><strong id="trade-picker-title">어떤 상품을 살까요?</strong><button type="button" data-trade-close aria-label="상품 선택 닫기">×</button></div><p class="notice">두 상품을 함께 선택할 수 있습니다.<br>상품당 최대 100만 원 · 현금이 부족하면 균등 배분</p><div class="trade-products">${options.map(a=>`<label class="buy-product"><input type="checkbox" value="${a}"><span>${a==='buy'?'삼성전자':'2배 레버리지'}<small data-estimate="${a}">선택 안 함</small></span></label>`).join('')}</div><p class="purchase-total" aria-live="polite"></p><button class="primary" data-buy-confirm disabled>상품을 선택해 주세요</button><button type="button" class="text-button" data-trade-close>취소</button>`;
 const selected=()=>[...dialog.querySelectorAll('input:checked')].map(input=>input.value);
 const update=()=>{const choices=selected(),plan=purchasePlan2(s,choices),valid=choices.length&&plan.every(p=>p.quantity>0);for(const a of options){const item=plan.find(p=>p.action===a);dialog.querySelector(`[data-estimate="${a}"]`).textContent=item?`${money(item.cost)} · ${item.quantity}주`:'선택 안 함';}const total=plan.reduce((sum,p)=>sum+p.cost,0);dialog.querySelector('.purchase-total').textContent=choices.length?(valid?`총 ${money(total)} · 남는 현금 ${money(s.cash-total)}`:'두 상품을 함께 사기에는 현금이 부족합니다.'):`남은 현금 ${money(s.cash)}`;const confirm=dialog.querySelector('[data-buy-confirm]');confirm.disabled=!valid;confirm.textContent=choices.length?`${choices.length}개 상품 매수하기`:'상품을 선택해 주세요';};
 dialog.addEventListener('change',update);dialog.querySelector('[data-buy-confirm]').onclick=()=>{const choices=selected();if(!choices.length||purchasePlan2(s,choices).some(p=>p.quantity<1))return;app.dispatchEvent(new CustomEvent('stage2-trade-selected',{detail:choices.length===2?'buyBoth':choices[0]}));};
 app.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.querySelectorAll('[data-trade-close]').forEach(b=>b.onclick=()=>dialog.close());update();dialog.showModal();
}
function render(){if(s.phase==='support'&&s.needSurvey&&!cashShort2(s)){s={...s,phase:'play',needSurvey:false,needSurveyShown:false};save();}try{if(localStorage.getItem('prototype-feedback-used-stage2')==='yes')s.needSurveyShown=true;}catch{}const scene=SCENES2[s.turn],v=value2(s);app.innerHTML=`<header><div class="header-start"><button type="button" class="back-button" data-stage2-action="back" ${s.undo?.length?'':'disabled'}>← 뒤로</button><button type="button" class="back-button" data-stage2-action="forward" ${forwardStates.length?'':'disabled'}>앞으로 →</button></div><span class="turn">2스테이지 · ${s.phase==='intro'?'시작하기':`${s.turn+1} / ${SCENES2.length}`}</span></header>`;
 if(s.phase==='result'){app.innerHTML+=`<section class="screen result"><p class="chapter">1 · 2스테이지 누적 결과</p><h2>마지막 장면까지 도착했습니다.</h2>${hud()}<div class="balance">${row('최초 시작 자산',money(s.initialCapital??START))}${row('누적 추가 지원금',money(s.grants))}${row('받은 월급',money(s.salaryIncome||0))}${row('누적 생활비',money(s.spent))}${row('남은 순자산',money(v.equity))}${row('투자로 생긴 손익',money(v.profit))}</div><div class="control-tip"><h3>더 크게 오르고, 더 크게 떨어집니다.</h3>레버리지 상품은 같은 방향으로 움직여도 가격 변화가 더 큽니다. 기대하는 수익뿐 아니라 감당할 수 있는 하락폭도 생각해 보세요.</div>${holdingsIndicator()}<button class="primary" data-stage2-action="restart">1스테이지부터 다시 하기</button></section>`;}
 else if(s.phase==='support'){app.innerHTML+=`<section class="screen play">${hud()}<h2 class="scene-title">${s.appFeedback?'앱에 대한 의견 남기기':'다음 선택을 위한 지원금'}</h2><p class="dialogue">${s.appFeedback?'앱을 사용하면서 좋았던 점이나 불편했던 점을 알려 주세요.':s.needSurvey?'지금까지의 선택을 돌아보고 답하면 게임 지원금 500만 원을 받을 수 있습니다.':'생활비를 마련하기 위해 보유 주식이 있었다면 정리했습니다. 부족한 돈은 지원받아 계속 진행할 수 있습니다.'}</p><form class="stage2-form">${choiceHistory(s.history||[],SCENES2,2)}<label for="reflection">현금이 필요한 지금, 어떤 선택을 바꾸고 싶나요?</label><select id="reflection" required><option value="">선택해 주세요</option><option>투자할 때 현금을 더 남기고 싶어요</option><option>레버리지 상품에 투자하는 금액을 줄이고 싶어요</option><option>생활비와 추가 지출을 먼저 확인하고 싶어요</option><option>지금까지의 선택을 유지하고 싶어요</option><option>아직 모르겠어요</option></select><label for="reflection-note">그렇게 생각한 이유 (선택)</label><textarea id="reflection-note" maxlength="300"></textarea><p class="notice">응답은 이 브라우저에만 저장됩니다. ${s.needSurvey?'지금 답하지 않고 계속할 수도 있습니다.':'응답 여부와 관계없이 같은 지원금을 받습니다.'}</p><button class="primary" type="submit">답하고 ${money(s.needSurvey?5000000:Math.max(1000000,bill2(s)-s.cash))} 받기</button><button type="button" class="text-button" data-stage2-action="skip">${s.needSurvey?'나중에 하기':'응답하지 않고 같은 지원금 받기'}</button></form></section>`;}
 else{const labels={feedback:['앱에 대한 의견 남기기','의견 참여 · 250만 원'],ask:['선택을 돌아보고 지원금 받기','선택 회고 · 500만 원'],rest:['쉬어 간다','건강 +15'],hold:['그대로 둔다','현재 보유 유지'],sell:['삼성전자를 판다','삼성전자 전량 매도'],buy:['삼성전자를 산다','최대 100만 원'],leverBuy:['레버리지를 산다','최대 100만 원'],leverSell:['레버리지를 판다','레버리지 전량 매도'],next:['다음 장면으로',''],pay:['생활비를 결제한다',s.cash>=bill2(s)?'현금으로 '+money(bill2(s)):'부족한 만큼 상품을 팔아 결제']};app.innerHTML+=`<section class="screen play">${hud()}<div class="progress"><i style="width:${s.turn/SCENES2.length*100}%"></i></div><h2 class="scene-title">${scene.title}</h2><p class="dialogue">${scene.kind==='bill'?'월급 300만 원이 입금됐습니다. ':''}${scene.text}</p>${s.medical&&s.turn<=s.medical.bill?'<p class="market-note" role="status">건강 악화로 병원비 50만 원이 다음 생활비에 추가됐습니다. 회복해도 이미 발생한 병원비는 남습니다.</p>':''}${s.turn===0?'<p class="scene-fact">매 턴 삼성전자 가격 변동률의 2배로 움직이는 가상 상품입니다.</p>':''}${holdingsIndicator()}${scene.kind==='trade'&&s.turn>0?tradeChoices():`<div class="choices">${(s.turn===0?['hold','leverBuy']:actions2(s)).map(a=>`<button class="choice ${a==='pay'?'buy':''}" data-stage2-action="${a}" ${s.turn===0&&a==='leverBuy'&&s.cash<leveragePrice2(s)?'disabled':''}>${s.turn===0?(a==='hold'?'지켜본다':'투자해 본다'):labels[a][0]}${s.turn===0?'':`<small>${labels[a][1]}</small>`}</button>`).join('')}</div>`}<div class="stage2-secondary">${[...(cashShort2(s)&&!s.needSurveyShown?['ask']:[]),...(s.turn===7&&!appFeedbackUsed()&&!(s.answers||[]).some(a=>a.kind==='app-feedback')?['feedback']:[])].map(a=>`<button class="text-button" data-stage2-action="${a}">${labels[a][0]} · ${labels[a][1]}</button>`).join('')}</div></section>`;}
 if(openResource){const dialog=app.querySelector('#resource-detail');dialog.style.inset='0';dialog.style.margin='auto';dialog.showModal();} if(s.phase==='support'&&s.appFeedback){app.querySelector('.stage2-form').innerHTML=appFeedbackFields()+'<p class="notice">응답은 이 브라우저에만 저장됩니다. 의견 참여 지원금 250만 원 · 스테이지당 1회</p><button class="primary" type="submit">의견 남기고 지원금 받기</button><button type="button" class="text-button" data-stage2-action="skip">나중에 하기</button>';} if(s.phase==='support'&&!s.needSurvey&&!s.appFeedback){const form=app.querySelector('.stage2-form');if(form)form.innerHTML='<p class="notice">자금이 부족해도 스테이지를 계속할 수 있습니다.</p><button type="button" class="primary" data-stage2-action="skip">지원금 받고 계속하기</button>';} const responseForm=app.querySelector('.stage2-form');if(responseForm&&(s.needSurvey||s.appFeedback)){responseForm.insertAdjacentHTML('afterbegin',privacyNotice());} window.scrollTo(0,0);}
app.addEventListener('stage2-trade-selected',e=>{const button=document.createElement('button');button.dataset.stage2Action=e.detail;app.append(button);button.click();button.remove();});
app.addEventListener('click',e=>{if(!s)return;const trade=e.target.closest('[data-stage2-trade]');if(trade){openTrade(trade.dataset.stage2Trade);return;}const resource=e.target.closest('[data-stage2-resource]');if(resource){openResource=resource.dataset.stage2Resource;render();return;}if(e.target.closest('[data-stage2-close]')){openResource=null;app.querySelector('dialog')?.close();return;}const action=e.target.closest('[data-stage2-action]')?.dataset.stage2Action;if(!action)return;openResource=null;if(action==='back'){if(s.undo?.length){forwardStates.push(structuredClone(s));s={...s.undo.at(-1),undo:s.undo.slice(0,-1)};save();render();}return;}if(action==='forward'){if(forwardStates.length){s=forwardStates.pop();save();render();}return;}if(action!=='export')forwardStates=[];if(!['export','restart'].includes(action)){const snapshot=structuredClone(s);delete snapshot.undo;s={...s,undo:[...(s.undo||[]),snapshot]};}if(action==='ask'&&!cashShort2(s))return;if(action==='ask'&&localStorage.getItem('prototype-feedback-used-stage2')==='yes')return;if(action==='feedback'){if(s.turn!==7||appFeedbackUsed()||(s.answers||[]).some(a=>a.kind==='app-feedback'))return;s={...s,phase:'support',appFeedback:true,needSurvey:false};}else if(action==='ask')s={...s,phase:'support',needSurvey:true,needSurveyShown:true};else if(action==='start')s={...s,phase:'play'};else if(action==='restart'){clearStage2();s=null;onRestart();return;}else if(action==='ack')s={...s,receipt:null};else if(action==='skip')s=s.needSurvey||s.appFeedback?{...s,needSurvey:false,appFeedback:false,needSurveyShown:(s.answers||[]).some(a=>a.kind==='reflection-need'||(!a.kind&&a.amount===5000000)),phase:'play'}:support2(s,'응답하지 않음');else if(action==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='stage2-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}else s=step2(s,action);save();render();});
app.addEventListener('cancel',()=>{openResource=null;},true);
app.addEventListener('submit',e=>{if(!s||!e.target.matches('.stage2-form'))return;e.preventDefault();if(!e.target.reportValidity())return;const reflection=app.querySelector(s.appFeedback?'#app-feedback':'#reflection')?.value,note=app.querySelector(s.appFeedback?'#app-feedback-note':'#reflection-note')?.value||'';if(!reflection)return;if(s.appFeedback){if(appFeedbackUsed())return;try{localStorage.setItem('prototype-app-feedback-stage2','yes');}catch{}}if(s.needSurvey){try{if(localStorage.getItem('prototype-feedback-used-stage2')==='yes'){s={...s,phase:'play',needSurvey:false,needSurveyShown:true};save();render();return;}localStorage.setItem('prototype-feedback-used-stage2','yes');}catch{}}forwardStates=[];s=support2(s,{reflection,note,consent:consentRecord()});save();render();});
